#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    ir1,            sensorLineFollower)
#pragma config(Sensor, in2,    ir2,            sensorLineFollower)
#pragma config(Sensor, in3,    ir3,            sensorLineFollower)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port2,           motorA,        tmotorVex393, PIDControl, encoder, encoderPort, I2C_1, 1000)
#pragma config(Motor,  port3,           motorB,        tmotorVex393, PIDControl, encoder, encoderPort, I2C_2, 1000)
#pragma config(Motor,  port4,           motorC,        tmotorVex393, PIDControl, encoder, encoderPort, I2C_3, 1000)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//



task main()
{
	bLCDBacklight = false;
	while (true)
	{
		clearLCDLine(0);
		displayLCDNumber(0, 0, SensorValue[in1]) ;
				wait1Msec(500);
	}
}
