#pragma config(Sensor, in1,    ir1,            sensorNone)
#pragma config(Sensor, in2,    ir2,            sensorLineFollower)
#pragma config(Sensor, in3,    ir3,            sensorLineFollower)
#pragma config(Sensor, dgtl1,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           motorA,        tmotorVex393, openLoop)
#pragma config(Motor,  port3,           motorB,        tmotorVex393, openLoop)
#pragma config(Motor,  port4,           motorC,        tmotorVex393, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
typedef struct
{
	byte dev ;
	byte reg ;
} SendMessageT ;
typedef struct
{
	byte data[20] ;
} RecvMessageT ;

task main()
{
	//while(nLCDButtons == 0) {}

	//wait1Msec(2000);

 // motor[motorA] = 30 ;
	//motor[motorB] = 30 ;
	//motor[motorC] = 30 ;

	SendMessageT sendMsg ;
	sendMsg.dev = 0x60 ;
	sendMsg.reg = 0x08 ;
	RecvMessageT rcvMsg ;
	//asm(opcdSendI2CMsg, byte(sysFuncSendI2cMsg), variableRefByte(sendMsg), variable(20));
	sendI2CMsg( (byte)sendMsg, 20);
	wait1Msec(10) ;
  readI2CReply( rcvMsg.data[0], 20);

}
